services:
  postgres:
    image: postgres:15
    container_name: movie-postgres
    environment:
      POSTGRES_DB: movie_storage
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - movie-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U movie_user -d movie_storage" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: movie-minio
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - movie-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  storage-service:
    build: ./storage-service
    container_name: storage-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movie_storage
      MINIO_ENDPOINT: http://minio:9000
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - movie-network

  sync-service:
    build: ./sync-service
    container_name: sync-service
    ports:
      - "8082:8082"
    depends_on:
      - storage-service
    networks:
      - movie-network

volumes:
  postgres_data:
  minio_data:

networks:
  movie-network:
    driver: bridge
